<?php

function placessearch_menu() {

  $items['success'] = array(
  'title' => 'Success',
  'page callback' => 'places_search',
  'access callback' => TRUE,
  'type' => MENU_CALLBACK,
  );
  $items['places'] = array(
  'title' => 'Places',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('places_form'),
  'access callback' => TRUE,
  'type' => MENU_NORMAL_ITEM,
  );
  return $items;
 }

 function places_form() {
   $form['attraction'] = array(
    '#title' => 'Attraction',
    '#type' => 'textfield',
    '#description' => t('Please enter the type of attraction you would like to visit'),
    '#required' => TRUE,
    );
    $form['city'] = array(
    '#title' => 'city',
    '#type' => 'textfield',
    '#description' => t('Please enter a city'),
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    );
    return $form;
    }

function places_form_submit($form, &$form_state) {
    $city = $form_state['values']['city'];
    $attraction = $form_state['values']['attraction'];
    $_SESSION['city'] = $city;
    $_SESSION['attraction'] = $attraction;
    $form_state['redirect'] = 'success';
    }

function places_search() {
        $output = '';
        $rating = '';
        $api_key = 'AIzaSyBYHchyBbsoRlietf6HpsRWTFN4p7RE5V4';
        $attraction = $_SESSION['attraction'];
        if(str_word_count($attraction) > 1) {
        $attraction = preg_replace('/\s+/', '', $attraction);
        }else {
        $attraction = $attraction;
        }

        $city = $_SESSION['city'];
        if(str_word_count($city) > 1) {
        $city = preg_replace('/\s+/', '', $city);
        }else {
        $city = $city;
        }

        $api_call ='https://maps.googleapis.com/maps/api/place/textsearch/json?query='.$attraction.'+in+'.$city.'&key='.$api_key;
        var_dump($api_call);

        $result_string = file_get_contents($api_call);
        $result_array = json_decode($result_string, TRUE);
        var_dump($result_array);
        // if(empty($result_array['results'] === 'false')) {
        // for ($i=0; $i < count($result_array['results']); $i++) {
        //     $address = $result_array['results'][$i]['formatted_address'];
        //     $name = $result_array['results'][$i]['name'];
        //     $place_id = $result_array['results'][$i]['place_id'];
        //       if(empty((string)$result_array['results'][$i]['rating']) === false) {
        //           $rating = (string)$result_array['results'][$i]['rating'];
        //       }else {
        //         $rating = "Sorry no rating";
        //       }
            $output=$output.<<<EOD
            <h2>$name</h2>
            <h4>Address: $address </h4>
            <h4>Rating: $rating </h4>
EOD;
        // }
        // } else {
        //     $output = "Sorry no results";
        // }
        return $output;
    }
